config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root 'welcome#index'
  resource :welcome, only: :index
  resources :courses do
    resources :units, only: [:new, :create]
  end
  resources :units, only: [:show, :edit, :destroy, :update] do
    get 'toggle_visibility'
    resources :assignments, only: [:new, :create]
  end
  resources :assignments, only: [:show, :edit, :destroy, :update]
  resources :users, only: [:show, :edit, :index, :update]

  resources :class_periods, only: [:index, :new, :create, :edit, :show, :update, :destroy] do
    resources :students, only: :destroy, to: 'class_periods#remove_student'

    member do
      get 'manage_students'
      patch 'add_students'
    end
  end

  resources :student_welcome, only: :index
  resources :teacher_welcome, only: :index

  resources :class_assignment, only: :update

  get '/gradebooks/:id/unit/:unit_id', to: 'gradebooks#show', as: :gradebook

  get '/playbooks/student/:student_id/class_period/:class_period_id/unit/:unit_id',
      to: 'playbooks#show', as: :playbook
end

app/models/ar/class_period.rb
class ClassPeriod < ApplicationRecord
  belongs_to :course, inverse_of: :class_periods

  has_many   :teacher_classes, dependent: :destroy
  has_many   :teachers, -> { order(:last_name) }, through: :teacher_classes

  has_many   :student_classes, dependent: :destroy
  has_many   :students, -> { order(:last_name) }, through: :student_classes

  delegate :assignments, :units, to: :course

  def addable_students
    Student.all - students
  end

  def teachers
    super.presence || [NullTeacher.new]
  end

  def teacher_names
    teachers.map(&:name).sort.to_sentence
  end
end

app/controllers/class_periods_controller.rb
class ClassPeriodsController < ApplicationController
  def index
    @class_periods = ClassPeriod.all.includes(:course, :teachers).references(:teachers)
  end

  def show
    @class_period = ClassPeriod.find(params[:id])
  end

  def new
    #@course = Course.find params[:course_id]
    @class_period = ClassPeriod.new
  end

  def create
    @class_periods = ClassPeriod.create!(class_period_params)
    redirect_to class_periods_path
  end

  def edit
    @class_period = ClassPeriod.find(params[:id])
  end

  def update
    @class_period = ClassPeriod.find(params[:id])
    if @class_period.update_attributes(class_period_params)
      redirect_to class_periods_path
    else
      render :edit
    end
  end

  def destroy
    @class_period = ClassPeriod.find(params[:id])
    @class_period.destroy
    redirect_to class_periods_path
  end

  def manage_students
    @class_period = ClassPeriod.find(params[:id])
  end

  def remove_student
    unenrolled = Registrar.new.unenroll(class_period_id: params[:class_period_id], student_id: params[:id])
    if unenrolled
      @removed_student = unenrolled.student
      flash[:success] = 'Student was removed from class period'
    else
      flash[:error] = 'Student was not removed from class period'
    end

    respond_to do |format|
      format.html { redirect_to :manage_students }
      format.js
    end
  end

  def add_students
    @class_period = ClassPeriod.find(params[:id])
    Registrar.new.enroll(class_period_id: params[:id], students: class_period_params[:student_ids])

    redirect_back(fallback_location: manage_students_class_period_path(class_period: @class_period))
  end

  private

  def class_period_params
    params.require(:class_period).permit(:period, :course_id, student_ids: [], teacher_ids: [])
  end
end

app/helpers/class_period_helper.rb
module ClassPeriodHelper
  include CourseHelper

  def class_period_short_label(class_period)
    "#{class_period.course.name.capitalize} Period: #{class_period.period}"
  end

  def class_period_label(class_period)
    "#{class_period_short_label(class_period)} - #{taught_by_teachers(class_period)}"
  end

  def taught_by_teachers(class_period)
    "Taught by: #{class_period.teacher_names}"
  end
end

app/views/class_periods/_form.html.erb
<div class='panel panel-primary'>
  <div class='panel-heading'>
    <div class='panel-title'>
      <h1><%= (class_period.new_record?) ? 'New Class Period' : class_period_short_label(class_period) %></h1>
    </div>
  </div>

  <div class='panel-body'>
    <%= semantic_form_for class_period do |form| %>
      <%= form.inputs do %>
        <%= form.input :course, input_html: {class: 'chosen-select'} %>
        <%= form.input :teachers, input_html: {class: 'chosen-select'} %>
        <%= form.input :period %>
      <% end %>
      <%= form.actions do %>
        <%= form.action :submit %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/class_periods/edit.html.erb
<%= render partial: 'form', locals: { class_period: @class_period } %>

app/views/class_periods/index.html.erb
<% if @class_periods.present? %>
  <div class='panel panel-primary list-panel'>
    <div class='panel-heading'>
      <div class='panel-title'>
        <div class='row'>
          <div class='col-md-6'>
            <h1>Class Periods</h1>
          </div>
          <div class='col-md-6'>
            <div class='pull-right'>
              <%= link_to 'New Class Period', new_class_period_path, class: 'new btn btn-primary' %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class='panel-body'>
      <ul class='class-periods list-group'>
        <% @class_periods.each do |class_period| %>
          <li class='class-period list-group-item clearfix'>
            <%= link_to class_period_label(class_period), class_period_path(class_period) %>
            <div class='btn-group pull-right'>
              <%= link_to edit_class_period_path(class_period), class: 'btn btn-default' do %>
                <%= fa_icon 'pencil', text: 'Edit' %>
              <% end %>
              <%= link_to manage_students_class_period_path(class_period) , class: 'btn btn-default' do %>
                <%= fa_icon 'users', text: 'Manage Students' %>
              <% end %>
              <%= link_to class_period_path(class_period), method: :delete, class: 'btn btn-default',
                          data: { confirm: "Are you sure you want to delete class period: #{class_period.period}" } do %>
                <%= fa_icon 'times', text: 'Delete' %>
              <% end %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
<% else %>
  <% if Course.blank? %>
    <%= render partial: 'shared/jumbo',
                        locals: {
                        jumbo_text: 'There are no courses!',
                        button_text: 'Create One',
                        url: new_course_path } %>
  <% else %>
    <%= render partial: 'shared/jumbo',
                        locals: {
                        jumbo_text: 'There are no class periods!',
                        button_text: 'Create One',
                        url: new_class_period_path } %>
  <% end %>
<% end %>

app/views/class_periods/manage_students.html.erb
<div class='row'>
  <div class='col-xs-12 col-md-8'>
    <div class='panel panel-primary list-panel'>
      <div class='panel-heading'>
        <div class='panel-title'>
          <h1>Students in <%= @class_period.course.name%></h1>
        </div>
      </div>

      <div class='panel-body'>
        <ul class='students list-group'>
          <% @class_period.students.each do |student| %>
            <li id='student-<%=student.id%>'class='list-group-item'>
              <div class='row'>
                <div class='col-xs-6 col-md-8'>
                  <%= student.display_name %>
                </div>
                <div class='col-xs-6 col-md-4'>
                  <%= link_to class_period_student_path(@class_period, student), remote: true, method: :delete, class: 'pull-right btn btn-default',
                    data: { confirm: "Removing #{student.name} from #{class_period_short_label(@class_period)} will permanently erase all assignment and grade records, are you sure?" } do %>
                    <%= fa_icon 'times', text: 'Remove' %>
                  <% end %>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class='col-xs-12 col-md-4'>
    <div class='panel panel-default add-students'>
      <div class='panel-heading'>
        <div class='panel-title'>
          <h2><small>Add Students</small></h2>
        </div>
      </div>
      <div class='panel-body'>
        <%= semantic_form_for @class_period, url: add_students_class_period_path do |form| %>
          <%= form.inputs do %>
            <%= form.input :students, as: :select, collection: @class_period.addable_students, input_html: {multiple: 'multiple', class: 'chosen-select'} %>
          <% end %>
          <%= form.actions do %>
            <%= form.action :submit, label: 'Add Students' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/class_periods/new.html.erb
<%= render partial: 'form', locals: { class_period: @class_period } %>

app/views/class_periods/remove_student.js.erb
$('#student-<%= @removed_student.id %>').remove();

app/views/class_periods/show.html.erb
<div class='panel panel-primary'>
  <div class='panel-heading'>
    <div class='panel-title'>
      <h1><%= class_period_short_label @class_period %></h1>
    </div>
  </div>
  <div class='panel-body'>
    <span><%= taught_by_teachers(@class_period) %></span>
  </div>
</div>

<div class='panel panel-primary list-panel'>
  <div class='panel-heading'>
    <div class='panel-title'>
      <h2>Students</h2>
    </div>
  </div>
  <div class='panel-body'>
    <ul class='students list-group'>
      <% @class_period.students.each do |student| %>
        <li class='list-group-item'><%= student.display_name %></li>
      <% end %>
    </ul>
  </div>
</div>