config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root 'welcome#index'
  resource :welcome, only: :index
  resources :courses do
    resources :units, only: [:new, :create]
  end
  resources :units, only: [:show, :edit, :destroy, :update] do
    get 'toggle_visibility'
    resources :assignments, only: [:new, :create]
  end
  resources :assignments, only: [:show, :edit, :destroy, :update]
  resources :users, only: [:show, :edit, :index, :update]

  resources :class_periods, only: [:index, :new, :create, :edit, :show, :update, :destroy] do
    resources :students, only: :destroy, to: 'class_periods#remove_student'

    member do
      get 'manage_students'
      patch 'add_students'
    end
  end

  resources :student_welcome, only: :index
  resources :teacher_welcome, only: :index

  resources :class_assignment, only: :update

  get '/gradebooks/:id/unit/:unit_id', to: 'gradebooks#show', as: :gradebook

  get '/playbooks/student/:student_id/class_period/:class_period_id/unit/:unit_id',
      to: 'playbooks#show', as: :playbook
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all.includes(:units)
  end

  def show
    @course = Course.find(params[:id])
    @units = @course.units.includes(:assignments)
  end

  def new
    @course = Course.new
  end

  def create
    Course.create!(course_params)
    redirect_to courses_path
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    if @course.update_attributes(course_params)
      redirect_to courses_path
    else
      render :edit
    end
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    redirect_to courses_path
  end

  private

  def course_params
    params.require(:course)
          .permit(:name, :year)
  end

end

app/views/courses/_form.html.erb
<div class='panel panel-primary'>
  <div class='panel-heading'>
    <div class='panel-title'>
      <h1><%= (course.new_record?) ? 'New course' : course.name %></h1>
    </div>
  </div>

  <div class='panel-body'>
    <%= semantic_form_for @course do |form| %>
      <%= form.inputs do %>
        <%= form.input :name %>
        <%= form.input :year %>
      <% end %>
      <%= form.actions do %>
        <%= form.action :submit %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/courses/edit.html.erb
<%= render partial: 'form', locals: { course: @course } %>

app/views/courses/index.html.erb
<% if @courses.present? %>
  <div class='panel panel-primary list-panel'>
    <div class='panel-heading'>
      <div class='panel-title'>
        <h1>Courses</h1>
        <div class='pull-right'>
          <%= link_to 'New Course', new_course_path, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
    <div class='panel-body'>
      <ul class='courses list-group'>
        <% @courses.each do |course| %>
          <li data-course-id=<%= course.id %> class='course list-group-item clearfix'>
            <div class='btn-group pull-right'>
              <%= link_to edit_course_path(course), class: 'btn btn-default' do %>
                <%= fa_icon 'pencil', text: 'Edit' %>
              <% end %>
              <%= link_to course_path(course), method: :delete, class: 'btn btn-default',
                data: { confirm: "Are you sure you want to delete: #{course.name}" } do %>
                <%= fa_icon 'times', text: 'Delete' %>
              <% end %>
            </div>
            <strong class='block'><a href="<%= course_path(course) %>"><%= course %></a></strong>
            <small class='hide-overflow'>
              <strong>Units:</strong> <%= course.units.map(&:to_s).join(', ').presence || 'none' %>
            </small>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
<% else %>
  <%= render partial: 'shared/jumbo',
                      locals: {
                      jumbo_text: 'There are no courses!',
                      button_text: 'Create One',
                      url: new_course_path } %>
<% end %>

app/views/courses/new.html.erb
<%= render partial: 'form', locals: { course: @course } %>

app/views/courses/show.html.erb
<% if @course.units.present? %>
  <div class='panel panel-primary list-panel'>
    <div class='panel-heading'>
      <div class='panel-title'>
        <div class='row'>
          <div class='col-md-6'>
            <h1><%= @course %></h1>
          </div>
          <div class='col-md-6'>
            <div class='pull-right'>
              <%= link_to 'New Unit', new_course_unit_path(@course), class: 'new nit btn btn-primary' %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class='panel-body'>
      <ul class='units list-group'>
        <% @units.each do |unit| %>
          <li data-unit-id=<%=unit.id%> class='unit list-group-item clearfix'>
            <div class='btn-group pull-right'>
              <%= link_to unit_toggle_visibility_path(unit), class: 'btn btn-default toggle_visibility' do %>
                <% if unit.visible %>
                  Hide from Students
                <% else %>
                  Show to Students
                <% end %>
              <% end %>
              <%= link_to edit_unit_path(unit), class: 'btn btn-default' do %>
                <%= fa_icon 'pencil', text: 'Edit' %>
              <% end %>
              <%= link_to unit_path(unit), method: :delete, class: 'btn btn-default',
                  data: { confirm: "Are you sure you want to delete: #{unit.name}" } do %>
                    <%= fa_icon 'times', text: 'Delete' %>
              <% end %>
            </div>
            <strong class='block'>
              <%= link_to unit.name, unit_path(unit)%>
              <small>[<%= unit.possible_points %> points possible]</small>
            </strong>
            <span class="visiblitiy"><%=unit.visible ? 'Visible to Students' : 'Hidden from Students' %></span>
            <small class='hide-overflow'>
              <strong>Assignments:</strong> <%= unit.assignments.map(&:name).join(', ').presence || 'none' %>
            </small>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
<% else %>
  <%= render partial: 'shared/jumbo',
                      locals: {
                      jumbo_text: 'This course has no units!',
                      button_text: 'Create One',
                      url: new_course_unit_path(@course) } %>
<% end %>