config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root 'welcome#index'
  resource :welcome, only: :index
  resources :courses do
    resources :units, only: [:new, :create]
  end
  resources :units, only: [:show, :edit, :destroy, :update] do
    get 'toggle_visibility'
    resources :assignments, only: [:new, :create]
  end
  resources :assignments, only: [:show, :edit, :destroy, :update]
  resources :users, only: [:show, :edit, :index, :update]

  resources :class_periods, only: [:index, :new, :create, :edit, :show, :update, :destroy] do
    resources :students, only: :destroy, to: 'class_periods#remove_student'

    member do
      get 'manage_students'
      patch 'add_students'
    end
  end

  resources :student_welcome, only: :index
  resources :teacher_welcome, only: :index

  resources :class_assignment, only: :update

  get '/gradebooks/:id/unit/:unit_id', to: 'gradebooks#show', as: :gradebook

  get '/playbooks/student/:student_id/class_period/:class_period_id/unit/:unit_id',
      to: 'playbooks#show', as: :playbook
end

app/models/ar/unit.rb
class Unit < ApplicationRecord
  default_scope { order(order: :asc)  }

  scope :visible, -> { where(visible: true) }
  belongs_to :course, inverse_of: :units
  has_many :assignments, inverse_of: :unit, dependent: :destroy
  after_initialize :default_order

  def default_order
    return order if order.present?
    return nil if course.blank?

    self.order = course.units.length + 1
  end

  def possible_points
    assignments.map(&:possible_points).sum || 0
  end

  def to_s
    name
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  def index
    @units = Unit.all.order(:order)
  end

  def show
    @unit = Unit.find(params[:id])
  end

  def new
    @course = Course.find params[:course_id]
    @unit = Unit.new course: @course
  end

  def create
    @unit = Unit.create!(unit_params)
    redirect_to course_path @unit.course
  end

  def edit
    @unit = Unit.find(params[:id])
  end

  def update
    @unit = Unit.find(params[:id])
    if @unit.update_attributes(unit_params)
      redirect_to course_path @unit.course
    else
      render :edit
    end
  end

  def destroy
    @unit = Unit.find(params[:id])
    @unit.destroy
    redirect_to course_path @unit.course
  end

  def toggle_visibility
    @unit = Unit.find(params[:unit_id])
    @unit.toggle(:visible).save!
    redirect_to course_path @unit.course
  end

  private

  def unit_params
    params.require(:unit)
          .permit(:name, :order, :course_id)
  end

end

app/views/units/_form.html.erb
<div class='panel panel-primary'>
  <div class='panel-heading'>
    <div class='panel-title'>
      <h1><%= (unit.new_record?) ? 'New Unit' : unit.name %></h1>
    </div>
  </div>

  <div class='panel-body'>
    <%= semantic_form_for [course, unit] do |form| %>
      <%= form.inputs do %>
        <%= form.input :name %>
        <%= form.input :order %>
        <%= form.input :course_id, as: :hidden %>
      <% end %>
      <%= form.actions do %>
        <%= form.action :submit %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/units/_form_item.html.erb
<%= form.label :name, 'Name' %>
<%= form.text_field :name %>
<%= form.label :order, 'Order' %>
<%= form.text_field :order %>

app/views/units/edit.html.erb
<%= render partial: 'form', locals: { course: @course, unit: @unit } %>

app/views/units/new.html.erb
<%= render partial: 'form', locals: { course: @course, unit: @unit } %>

app/views/units/show.html.erb
<% if @unit.assignments.present? %>
  <div class='panel panel-primary list-panel'>
    <div class='panel-heading'>
      <div class='panel-title'>
        <div class='row'>
          <div class='col-md-6'>
            <h1><%= @unit %> <small>[<%= @unit.possible_points %> points possible]</small></h1>
          </div>
          <div class='col-md-6'>
            <div class='pull-right'>
              <%= link_to 'New Assignment', new_unit_assignment_path(@unit), class: 'new btn btn-primary' %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class='panel-body'>
       <ul class='assignments list-group'>
         <% @unit.assignments.each do |assignment| %>
           <li data-assignment-id=<%=assignment.id%> class='assignment list-group-item clearfix'>
             <div class='btn-group pull-right'>
               <%= link_to edit_assignment_path(assignment), class: 'btn btn-default' do %>
                 <%= fa_icon 'pencil', text: 'Edit' %>
               <% end %>
               <%= link_to assignment_path(assignment), method: :delete, class: 'btn btn-default',
                           data: { confirm: "Are you sure you want to delete: #{assignment.name}" } do %>
                 <%= fa_icon 'times', text: 'Delete' %>
               <% end %>
             </div>
             <strong class='block'><%=assignment.name%></strong>
             <small>
               Points: <%=assignment.worksheet_points_possible%> - Stars: <%=assignment.star_points_possible%> -
               IXL: <%=assignment.ixl_points_possible%> - Notes: <%=assignment.notes_points_possible%> -
               Due Date: <%=assignment.due_at%>
             </small>
           </li>
         <% end %>
       </ul>
    </div>
  </div>
<% else %>
  <%= render partial: 'shared/jumbo',
                      locals: {
                      jumbo_text: 'There are no assignments!',
                      button_text: 'Create One',
                      url: new_unit_assignment_path(@unit) } %>
<% end %>