config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root 'welcome#index'
  resource :welcome, only: :index
  resources :courses do
    resources :units, only: [:new, :create]
  end
  resources :units, only: [:show, :edit, :destroy, :update] do
    get 'toggle_visibility'
    resources :assignments, only: [:new, :create]
  end
  resources :assignments, only: [:show, :edit, :destroy, :update]
  resources :users, only: [:show, :edit, :index, :update]

  resources :class_periods, only: [:index, :new, :create, :edit, :show, :update, :destroy] do
    resources :students, only: :destroy, to: 'class_periods#remove_student'

    member do
      get 'manage_students'
      patch 'add_students'
    end
  end

  resources :student_welcome, only: :index
  resources :teacher_welcome, only: :index

  resources :class_assignment, only: :update

  get '/gradebooks/:id/unit/:unit_id', to: 'gradebooks#show', as: :gradebook

  get '/playbooks/student/:student_id/class_period/:class_period_id/unit/:unit_id',
      to: 'playbooks#show', as: :playbook
end

app/views/layouts/_logged_in.html.erb
<li role='presentation'><%= link_to('Sign Out', destroy_user_session_path, method: :delete) %></li>

app/views/layouts/_navigation_bar.html.erb
<nav>
  <ul class='nav nav-pills'>
    <li role='presentation'><h1><%= link_to('Teachy!', root_path) %></h1></li>
    <li role='presentation' class='dropdown pull-right'>
      <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        Hi, <%= current_user.try(:first_name) || 'Guest' %> <span class="caret"></span>
      </a>
      <ul class='dropdown-menu'>
        <%= render partial: "layouts/#{current_user.class.to_s.downcase}" %>
      </ul>
    </li>
  </ul>
</nav>

app/views/layouts/_nilclass.html.erb
<span><%= link_to 'Sign In', new_user_session_path %></span>
<span><%= link_to "Sign in with Google", user_google_oauth2_omniauth_authorize_path %></span>

app/views/layouts/_student.html.erb
<%= render partial: 'layouts/logged_in' %>
<%= link_to 'Planning', planning_url if current_user.is_a? Teacher %>

app/views/layouts/_teacher.html.erb
<% if current_user.is_a? Teacher %>
  <li role='presentation'><%= link_to 'Manage Courses', courses_path %></li>
  <li role='presentation'><%= link_to 'Manage Class Periods', class_periods_path%></li>
  <li role="separator" class="divider"></li>
<% end %>
<%= render partial: 'layouts/logged_in' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Teachy</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class='<%= controller_name %> <%= action_name %>'>
    <div id='main-container' class='container'>
      <div class='row'>
        <div class='col-12'>
          <%= render 'layouts/navigation_bar' %>
        </div>
      </div>

      <div class='row'>
        <div class='col-12'>
          <%= yield %>
        </div>
      </div>
  </body>
</html>